fix: add an exception if executable not found
ansys/ansys-tools-path pull request #184
Opened 2024-05-06 21:38 UTC by dipinknair

Currently, if no executable found in default location when using `get_mechanical_path` , then we are returning `None`. This is causing issue when we call `version_from_path` where we give `path` as input. We do not have any check if path is None. 

Alternately we can avoid this exception and return `path` as empty string (as it is) it is instead of `None`. If that is the case then  `version_from_path` will take care of value error if `path` is `empty string`

2024-05-07 06:23 UTC, RobPasMue commented on src/ansys/tools/path/path.py
> +                raise Exception("{product} executable not found in default locations")
Why would you prefer to raise an Exception? I would rather handle properly the ``None`` value.

2024-05-13 17:03 UTC, koubaa commented on src/ansys/tools/path/path.py
>                      return exe_loc
as discussed this can be moved somewhere else

2024-05-13 18:34 UTC, koubaa requested changes
The message of the exception isn't actionable by the end user

2024-05-14 11:13 UTC, RobPasMue approved these changes
LGTM - although we could actively check for None as well. But this is more than enough

2024-05-31 12:58 UTC, RobPasMue commented
We should do a new release after #193 - thanks @nmalsang - what's the status here? We could include this PR as well.

2024-06-06 10:17 UTC, germa89 requested changes
LGTM. But I think the message could be more explicative.

2024-06-06 10:17 UTC, germa89 commented on src/ansys/tools/path/path.py
> +        raise ValueError("Provided path is not a string")
```suggestion
        raise ValueError(f"Provided path '{path}' is not a string.")
```

2024-06-12 13:22 UTC, merged