Fixing `_read_config_file`
ansys/ansys-tools-path pull request #42
Opened 2023-05-23 09:30 UTC by clatapie

Closes #41.

2023-05-23 16:01 UTC, germa89 requested changes
Please address my questions and we can merge after.

2023-05-23 16:01 UTC, germa89 commented on src/ansys/tools/path/path.py
> -        return find_mechanical(version, supported_versions)
Why are you removing this?

2023-05-23 16:01 UTC, germa89 commented on src/ansys/tools/path/path.py
> +        _migrate_config_file(product_name)
So I guess this is the key.

2023-05-23 16:01 UTC, germa89 commented on src/ansys/tools/path/path.py
> +LINUX_DEFAULT_DIRS = [["/", "usr", "ansys_inc"], ["/", "ansys_inc"]]
why are you removing this? I see it is not a common path. Have you check who added it? and why?

2023-05-23 16:01 UTC, germa89 commented on tests/test_path.py
> +    os.makedirs(old_settings_dir, exist_ok=True)
Very good!

2023-05-24 15:56 UTC, RobPasMue approved these changes

2023-05-24 15:57 UTC, merged